server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    topic: "message-topic"
    consumer:
      group-id: "consumer-group-1"
      auto-offset-reset: earliest